version: '3'
services:
  max-mysql:
    image: mysql:5.7
    container_name: max-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=test
    ports:
      - 3307:3306
    restart: always

  max_mini_project:
    image: life14ok/miniproject
    container_name: max-miniproject
    ports:
      - 8080:8080
    volumes:
      - .:/vol/development
    depends_on:
      - max-mysql
    links:
      - max-mysql
    environment:
      - PORT=8080
      - DATABASE_HOST=max-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=123456
      - DATABASE_NAME=test
      - DATABASE_PORT=3306


